#!/bin/bash 

# Transpile the TypeScript into CommonJS packaged JavaScript (using tsconfig.json settings)
tsc -p .

# Create a version for use in web browsers (including minified copy)
browserify src/window.js -o lib/state.js
minify lib/state.js

# Create documentation
jsdox --output doc lib/state.com.js
