#!/bin/bash 

VERSION='5.3.0'

tsc -p .

browserify src/web.js -o lib/state.js

minify lib/state.js

jsdox --output docs lib/state.com.js

#cp src/state.d.ts src/versions/state-$VERSION.d.ts
#cp src/state.js src/versions/state-$VERSION.js
#cp src/state.min.js src/versions/state-$VERSION.min.js
