#!/bin/bash 

VERSION='5.2.0'

tsc -d --noImplicitAny state.ts
minify state.js
jsdox --output ../docs state.js

cp state.d.ts versions/state-$VERSION.d.ts
cp state.js versions/state-$VERSION.js
cp state.min.js versions/state-$VERSION.min.js
